### ISSUE TITLE
Enable CRC calculation for non-8bit multiple input size

### ISSUE THREAD

**Issue by jdemel** [d-bahr/CRCpp#10]
I'd like to calculate a CRC checksum for e.g. 13 or 26 bit input.

I expect data to start with full bytes and then the last byte is not fully packed. e.g. [xxxx x000] for 13bit input. I'd like to skip the last 3 bit in a BitByBit calculation. How should I approach this?

**Comment by d-bahr** [comment]
Unfortunately I don't think that's possible in the current implementation because it works on the input byte-by-byte. However, I don't think it would be too difficult to add a new CalculateBitByBit() function. Do you happen to have any examples of 13 bit data and the corresponding CRC?

**Comment by jdemel** [comment]
The CRCs from #9 especially, the ones with 6, 11, and 24 bit width are supposed to work with any number of bits. So anything 5G physical layer related would be a use case.

Or did you ask for a specific configuration e.g.:
Use `CRC_6_NR` (`0x21, 0x00, 0x00, false, false`) with input
input: `1, 0, 1, 1, 1, 1, 0, 1,  0, 0, 0, 1, 0` in bits or `0xbd, 0x10`.
expected checksum: `1, 0, 1, 1, 1, 1` or `0x2f`.

For `CRC_11_NR`:
input: `1, 0, 1, 1, 1, 1, 0, 1,  0, 0, 0, 1, 0` in bits or `0xbd, 0x10`.
expected checksum: `1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0` or `0x06, 0xc8`.

Would it fit with your library to add a set of methods `CalculateBitByBit()` just like the `Calculate()` methods but the input size arg states number of bits? Then `CalculateRemainder` would be called on all bytes but the last one which receives special handling. Does the `Finalize` method need an update?

**Comment by d-bahr** [comment]
Thanks, those examples (input and expected checksum) are what I needed. I also grabbed a couple examples from USB 2.0 which uses a 5-bit CRC and 11-bit input. Should be enough for testing.

Having a `CalculateBitByBit()` (or `CalculateBits()`?) which takes the number of bits instead of bytes was exactly what I was thinking, and special-case the last n bits. I don't think `Finalize` needs to change because the remainder is already shifted into the correct position before it gets called.

I'm working on an implementation. Shouldn't take too long, fingers crossed.

**Comment by d-bahr** [comment]
Added a `CalculateBits()` function and added a couple of test cases which match the examples you gave. Also verified a test case from USB 2.0.
Here's how your examples would be coded:
```
const unsigned char data[] = { 0xBD, 0x10 };
uint8_t crc = CRC::CalculateBits(data, 13, CRC::CRC_6_NR());
// crc == 0x2F
...
uint16_t anotherCRC = CRC::CalculateBits(data, 13, CRC::CRC_11_NR());
// anotherCRC == 0x06C8
```
Multi-part CRCs also work.
Still need to update the documentation; I'll do that in a follow-up commit.
Note to self: it's possible to shuffle some code around so that the inner loops are in their own functions; this would reduce code size a bit but probably deter the compiler from unrolling the loops because they would need to be passed as parameters.

**Comment by jdemel** [comment]
Thanks a lot for your help!
