### ISSUE TITLE
Performance of CRC32-C

### ISSUE THREAD

**Issue by madduci** [d-bahr/CRCpp#8]
Hi

first of all, thanks for this implementation, finally I can try to be independent from Boost.

I have hit a performance issue concerning a legacy codebase where CRC32-C is used. The Boost version of it, known as crc_optimal, is ~45% faster than yours, even using definitions such as CRCPP_USE_CPP11 and CRCPP_BRANCHLESS. I'd like to ditch the Boost one for this implementation, but the slowdown seems pretty hard to digest.

**Comment by d-bahr** [comment]
Thanks for your interest in CRC++. I'd recommend using a lookup table, as that will significantly increase performance. Example is in the README.

Due to some of the optimizations in boost, I would expect boost to be on average slightly faster because a few small operations are done at compile time (in boost) instead of runtime (in CRC++), but in my testing the results were always within about 5%.

If you are using a lookup table and still seeing a significant performance difference, then I'd like to know your platform and compiler, and I can try to reproduce.

**Comment by d-bahr** [comment]
Lookup table snippet:

```
int main(int argc, char ** argv)
{
	const char myString[] = { 'H', 'E', 'L', 'L', 'O', ' ', 'W', 'O', 'R', 'L', 'D' };
	
	auto table = CRC::CRC_32_C().MakeTable();
	
	std::uint32_t crc;
	
	crc = CRC::Calculate(myString, sizeof(myString), table);
	
	std::cout << std::hex << crc;
	
	return 0;
}
```

Edit: for CRC32-C.

**Comment by madduci** [comment]
thanks for the fast reply. I'll try' to use the Lookup Table method, but I don't know if it will work, since I'm reading some external files and this legacy codebase computes a checksum of those files.

The performance hit can be experienced on latest VC++ 16.8 (2019) on Windows/x86_64 and on gcc (8-9-10/Linux x86_64). It looks like it's not a compiler issue itself.

On 100x iterations, with CRC++ I have the following results

```
real  2m27,320s
user  2m25,558s
sys   0m1,739s
```

with the boost::crc_optimal:

```
real  1m26,912s
user  1m25,559s
sys   0m1,352s
```

**Comment by madduci** [comment]
I've run the test with the Lookup Table method, actually it happens to be perform even worse, if I initialize it every time in the local method I have:

```
real  2m37,911s
user  2m36,043s
sys   0m1,733s
```

but initializing the Lookup Table at the beginning and marking it as constant, I have similar performance to Boost, which is what I was looking for!

```
real  1m32,824s
user  1m31,229s
sys   0m1,567s
```

**Comment by d-bahr** [comment]
Yes, the tests may perform worse with lookup tables because it has to spend time creating the tables, but then only runs a single small CRC check per table, so there's quite a bit of overhead.

If you can reuse the lookup table (by making it static or something), then that's how you'll get the best results.

Glad it works for you!

**Comment by madduci** [comment]
many thanks!
